name: "PlantUML generator"
description: "Generate plantUML diagrams"
author: "@holowinski"

inputs:
  args:
    description: "Arguments for PlantUML"
    required: true
    default: "-h"

runs:
  using: "docker"
  image: "docker://holowinski/plantuml:1.2020.22"
  args:
    - ${{ inputs.args }}
